apiVersion: v1
kind: ConfigMap
metadata:
  name: crawler-configmap
  namespace: yh-crawler  # 可以根据实际情况调整命名空间
data:
  app.ini: |
    [app]
    PageSize = 10
    JwtSecret = 233
    PrefixUrl = http://127.0.0.1:8000

    RuntimeRootPath = runtime/

    ImageSavePath = upload/images/
    # MB
    ImageMaxSize = 5
    ImageAllowExts = .jpg,.jpeg,.png

    ExportSavePath = export/
    QrCodeSavePath = qrcode/
    FontSavePath = fonts/

    LogSavePath = logs/
    LogSaveName = log
    LogFileExt = log
    TimeFormat = 20060102

    [server]
    #debug or release
    RunMode = debug
    HttpPort = 8000
    ReadTimeout = 60
    WriteTimeout = 60

    [database]
    Host = postgres
    Port = 5432
    User = postgres
    Password = 123456
    Dbname = crawler
    Sslmode = disable 
    ; Type = mysql
    ; User = root
    ; Password = rootroot
    ; Host = 127.0.0.1:3306
    ; Name = blog
    ; TablePrefix = blog_

    [redis]
    Host = 127.0.0.1:30379
    Password =
    MaxIdle = 30
    MaxActive = 30
    IdleTimeout = 200

    [k8s]
    KubeConfig = conf/kubeconfig.yaml
    DefaultNamespace = yh-crawler

    [docker]
    RegistryAddr = default.registry.tke-syyx.com
    RegistryDir = syyx-tpf
    RegistryUsername = tkestack
    RegistryPassword = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjQ4NzcyMTk4MjQsImp0aSI6ImY2ZjUiLCJpYXQiOjE3MjM2MTk4MjQsInVzciI6Imh1aXd1IiwidGVkIjoiZGVmYXVsdCJ9.HDaoynqt_LUiMKJF9Xjrie6OAft34mUriKoS6uyO6bXw-WlEY_Ot92fzmQM9B3c4WiIONLYokMojqF0lyXdiRfbOv6_HSiZLSN5pTBPdoF3OvxOpuaJmZayBDDjs2Luo0xTCMeqwC4CNLs1qbxBCuEVEbb7wugFdEjpUEA4IuyHG_tzprFkCdC-DBwCUtHA6xsRzQrcWVX70YhVg4T_WklkB7L4mYd7koI4yo0OykAbfjyAP5iSd3pldLzvpe058oFIhgug_H253fW2IGY5euWDbOC2qtJK_0yTzetXie5fUWf5EIuLKHLV76Yv45CsKvgdon3RYWik0EY3iSUOlKQ
    ForcePush = true
    ServerAddress = default.registry.tke-syyx.com
  

  kubeconfig.yaml: |
    apiVersion: v1
    clusters:
      - cluster:
          certificate-authority-data: >-
            LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeE1EUXhNekExTXpRMU4xb1hEVE14TURReE1UQTFNelExTjFvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTjh5CkJPb0YxU1RSTVFxT2FSMk1zd0cyMmhSNCtvUGppOFg3NmZBL09lMFd0VUl1c095RDJ0eGkvdnlOMElVWmdBcVoKbVpVTHEyWWx4ZXlQSkFsd3J6eFlvQWRaeS9QSVd3aC9id0xHVnpDREpoY1lLUjZRWVZkV2l3dHlpS3VPd0hJSwozbGtVUkVxc3pYZ2FUV2JMNUxBcGdyamtZYm1LV1RkemF0S0lURW1tRTFEVkxIbDhPU2s2cElEeWRCSXU5YXhiCkZQUkt6UHV1RU5CejhFS0ZCb3IvM3pyeEkxZlJkZDJIU0hOQk05NnRnUGJaWS9tQSs4cWNGSTV0UDZTL1VEN1kKdUlRSnp4cmlzZmh5SWxRQ2p3L3pkMXVJYkFTbUF4NG1pZU9RcktSa1FUK01rQUo3cHdEM3RKSzZMVDZzZitSeApoejhyUGJqU21IczV4NnU1NmVjQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFJMjlnSXQwZXlFd0FYNWxxeGFtbllJRVQ2K3oKdHdZWFlESlZHWUZob0RmSjZjNHJucGgvcXFzVWx2MnYrL0puZTZTRE9WU3FmZ2dxT1k3SW5TbTZsV0NSQi91YgpmWlhXYUl2akVpZXlUQ2tJYnFNejdZSDJ2ak9VdzJEYitDd2tLNmowbW1RTG5vam5vVXJhUndpU05CcmdudXlTCmc0dHZPZ0hCK3hoRWxGUG5VTzY4Mlh5QjluZC94cDBQb2Q5RHN4NXJ6MzdMbmc5WjZpNWh6cWUyS3hzUFBiVlUKT000ZURPb3I0RVlmZWZXTWpFMXFTMXU1R1FUOG1qQnhISzcrTC84Q2llVU1renphN2JyY0xQM3EwNGpQWnYrcQpYZExjWG9tNGJiYnpWVmoyWGVsRTE2MkZiRUlPZExXeE5VTlFnZzArcnk1SXVIVkxzWWxUS2QwVHE2VT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
          server: https://10.100.0.133:6443
        name: cls-mmhtkv54
    contexts:
      - context:
          cluster: cls-mmhtkv54
          user: cls-mmhtkv54-admin
        name: cls-mmhtkv54-context-default
    current-context: cls-mmhtkv54-context-default
    kind: Config
    preferences: {}
    users:
      - name: cls-mmhtkv54-admin
        user:
          token: 1r6LyTXUaqY4johIykjvWFTjK0o

  deamon.json: |
    {
      "registry-mirrors": [
        "https://wveb9fi0.mirror.aliyuncs.com",
        "http://hub-mirror.c.163.com",
        "https://registry.docker-cn.com"
      ],
      "insecure-registries": [
        "10.100.3.2:2443",
        "10.100.0.118",
        "default.registry.tke-syyx.com"
      ],
      "debug": true,
      "experimental": true,
      "ip-forward": true,
      "ip-masq": false,
      "iptables": true,
      "ipv6": false,
      "live-restore": true,
      "log-level": "debug",
      "log-driver": "json-file",
      "selinux-enabled": false,
      "dns": [
        "8.8.8.8",
        "1.1.1.1"
      ]
    }