apiVersion: apps/v1
kind: Deployment
metadata:
  name: crawler-deployment
  namespace: yh-crawler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crawler
  template:
    metadata:
      labels:
        app: crawler
    spec:
      dnsPolicy: "ClusterFirst"  # 设置为 None 以使用自定义 DNS 配置
      dnsConfig:
        nameservers:
          - 8.8.8.8
          - 1.1.1.1
      securityContext: # 这里是 Pod 的安全上下文 控制 Pod 或容器的安全属性（如用户、组、权限等）。
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
      containers:
        - name: crawler
          image: default.registry.tke-syyx.com/syyx-tpf/crawler:1.0.50
          securityContext:
            privileged: true
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: config-volume
              subPath: app.ini  # 指定 ConfigMap 中的文件名
              mountPath: /app/conf/app.ini
              readOnly: true
            - name: config-volume
              subPath: kubeconfig.yaml # 挂载 kubeconfig.yaml
              mountPath: /app/conf/kubeconfig.yaml
              readOnly: true
            - name: config-volume
              subPath: deamon.json  # 指定 ConfigMap 中的文件名
              mountPath: /etc/docker/daemon.json
              readOnly: true
          resources:
            requests:
              memory: "2000Mi"
              cpu: "1000m"
            limits:
              memory: "2000Mi"
              cpu: "1000m"
      volumes:
        - name: config-volume
          configMap:
            name: crawler-configmap   # 引用你创建的 ConfigMap 的名称
