apiVersion: apps/v1
kind: Deployment
metadata:
  name: crawler-deployment
  namespace: yh-crawler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crawler
  template:
    metadata:
      labels:
        app: crawler
    spec:
      containers:
        - name: crawler
          image: default.registry.tke-syyx.com/syyx-tpf/crawler:1.0
          ports:
            - containerPort: 8000