# apiVersion: batch/v1 #k8s版本需1.20以上
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: crawler-app-ssssss 
  namespace: yh-crawler 
  labels:
    app: crawler
    app-group: crawler-app
    execute-id: "77"
    job-group: crawler-app-ssssss
spec:
  schedule: '*/5 * * * *'  # 每天午夜执行一次
  startingDeadlineSeconds: 60  # Job 触发的最后期限
  concurrencyPolicy: Forbid  # 禁止并发执行
  successfulJobsHistoryLimit: 3  # 保留3个成功的Job历史记录
  failedJobsHistoryLimit: 1  # 保留1个失败的Job历史记录
  jobTemplate:
    spec:
      parallelism: 1  # 设置并行执行的 Job 数量
      completions: 1  # 完成任务的总数
      template:
        metadata:
          labels:
            app: crawler
        spec:
          ttlSecondsAfterFinished: 60
          containers:
          - name: crawler-app
            image: default.registry.tke-syyx.com/syyx-tpf/colly:2.4
            command:
              - ./myapp
            args:
              - --execute_id=77
              - --execute_name=啊啊
              - key_word=仓储
              - igore_word=这种
              - begin_time=1725963360
              - end_time=1725963367
              - aaa=bbb
          restartPolicy: Never
